// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Drive115Credential struct {
	ID        int32            `db:"id" json:"id"`
	UserID    int32            `db:"user_id" json:"user_id"`
	Name      string           `db:"name" json:"name"`
	Uid       string           `db:"uid" json:"uid"`
	Cid       string           `db:"cid" json:"cid"`
	Seid      string           `db:"seid" json:"seid"`
	Kid       string           `db:"kid" json:"kid"`
	IsActive  pgtype.Bool      `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           int32            `db:"id" json:"id"`
	Username     string           `db:"username" json:"username"`
	Email        string           `db:"email" json:"email"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID           int32            `db:"id" json:"id"`
	UserID       int32            `db:"user_id" json:"user_id"`
	SessionToken string           `db:"session_token" json:"session_token"`
	ExpiresAt    pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}
