// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Drive115 credentials management queries
	CreateDrive115Credentials(ctx context.Context, arg CreateDrive115CredentialsParams) (Drive115Credential, error)
	// User management queries
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// User session management queries
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	DeactivateAllUserDrive115Credentials(ctx context.Context, userID int32) error
	DeleteDrive115Credentials(ctx context.Context, id int32) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserSession(ctx context.Context, sessionToken string) error
	DeleteUserSessionsByUserID(ctx context.Context, userID int32) error
	GetActiveDrive115CredentialsByUserID(ctx context.Context, userID int32) ([]Drive115Credential, error)
	GetDrive115CredentialsByID(ctx context.Context, id int32) (Drive115Credential, error)
	GetDrive115CredentialsByUserID(ctx context.Context, userID int32) ([]Drive115Credential, error)
	GetDrive115CredentialsByUserIDAndName(ctx context.Context, arg GetDrive115CredentialsByUserIDAndNameParams) (Drive115Credential, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserSessionByToken(ctx context.Context, sessionToken string) (GetUserSessionByTokenRow, error)
	GetUserSessionsByUserID(ctx context.Context, userID int32) ([]UserSession, error)
	SetDrive115CredentialsActive(ctx context.Context, arg SetDrive115CredentialsActiveParams) error
	UpdateDrive115Credentials(ctx context.Context, arg UpdateDrive115CredentialsParams) (Drive115Credential, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
